version: '3.9'

services:
  goapi:
    build: .
    ports: 
      - "10000:10000"
    container_name: "go-api"
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"
    volumes:
      - $HOME/go/src/github.com/JulienOuell/GOAPI/test-db:/test-db
    container_name: mysql-db
